// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVE_H
#define DRIVE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
#include "AHRS.h"

class Drive: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> lDrive1;
	std::shared_ptr<CANTalon> lDrive2;
	std::shared_ptr<CANTalon> rDrive1;
	std::shared_ptr<CANTalon> rDrive2;
	std::shared_ptr<Solenoid> shiftGear;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	std::shared_ptr<AHRS> ahrs;

	Drive();
	void InitDefaultCommand();
	void Shift(bool high);
	void TankDrive(double lSpeed, double rSpeed);
	int GetLeftEnc();
	int GetRightEnc();

	void ResetNavX();
	float GetYaw();
	float GetXAccel();
	float GetYAccel();
	float GetXDisplacement();
	float GetYDisplacement();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
