// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SCALING_H
#define SCALING_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Scaling: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> scaleLift;
	std::shared_ptr<DigitalInput> scaleLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Scaling();
	enum class Position
	{
			POS_EXTENDED,
			POS_RETRACTED,
			POS_HOME
	};
	void InitDefaultCommand();
	void SetExtendSpeed(int speed);
	void ExtendToPoint(Position point);
	void ExtendToPoint(double point);
	bool IsExtendedToPoint(Position point);
	int GetScaleEnc();
	bool IsHome();
	void ResetScaling();
	double GetEncValueForPos(Position pos);
	void ChangeControlMode(CANTalon::ControlMode mode);
	double GetCurrent();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
