// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Scaling.h"
#include "../RobotMap.h"
#include "../Commands/Scaling/RunHookToPos.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

double scale_button_offset = 0;

Scaling::Scaling() : Subsystem("Scaling") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    scaleLift = RobotMap::scalingscaleLift;
    scaleLimit = RobotMap::scalingscaleLimit;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    ChangeControlMode(CANTalon::ControlMode::kPercentVbus);
}

void Scaling::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
//	SetDefaultCommand(new RunHookToPos());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Scaling::SetExtendSpeed(double speed){
	scaleLift->Set(speed);
}

void Scaling::ExtendToPoint(Position point){
	ExtendToPoint(GetEncValueForPos(point));
}

void Scaling::ExtendToPoint(double point){
	double error = point - GetScaleEnc();
	if (fabs(error) > 25)
	{
		if (fabs(error) > 1000)
		{
			scaleLift->Set(error / fabs(error));
		}
		else
		{
			scaleLift->Set(error / 1000);
		}
	}
	else
	{
		scaleLift->Set(0);
	}
}

int Scaling::GetScaleEnc(){
	return scaleLift->GetEncPosition();
}

bool Scaling::IsHome(){
	return scaleLimit->Get();
}

bool Scaling::IsExtendedToPoint(Position point){
	return fabs(scaleLift->GetEncPosition() - GetEncValueForPos(point)) < 30;
}

void Scaling::ResetScaling(){
	scaleLift->SetPosition(0);
}

double Scaling::GetEncValueForPos(Position pos){
	switch (pos)//Update values
	{
		case Position::POS_EXTENDED:
			return scale_button_offset - 10000;
		break;
		case Position::POS_RETRACTED:
			return scale_button_offset + 7350;
		break;
		case Position::POS_HOME:
			return 1;
		break;
		default:
			return -1;
	}
}

void Scaling::ChangeControlMode(CANTalon::ControlMode mode){
	scaleLift->SetControlMode(mode);
	if (mode == CANTalon::ControlMode::kPosition){
		scaleLift->SetPIDSourceType(PIDSourceType::kDisplacement);
		((std::shared_ptr<CANSpeedController>)scaleLift)->SetPID(SmartDashboard::GetNumber("scl_p_coeff", 1), SmartDashboard::GetNumber("scl_i_coeff", 0), SmartDashboard::GetNumber("scl_d_coeff", 0));
	}
}

double Scaling::GetCurrent(){
	return scaleLift->GetOutputCurrent();
}

void Scaling::ResetOffset()
{
	scale_button_offset = GetScaleEnc();
}
