// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTODRIVETURN_H
#define AUTODRIVETURN_H
#define TICKS_FROM_ANGLE 220

#include "Commands/Subsystem.h"
#include "../../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutoDriveTurn: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutoDriveTurn(double angle);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
//	int m_startTicksLeft;
//	int m_startTicksRight;
//	int m_ticks;
	double m_angle;
//	double m_speed;

	double m_integral;
	double m_derivative;

	static double m_integral_coeff;
	static double m_derivative_coeff;
	static double m_prop_coeff;

	int mod(int a, int n);
	double angle_diff(int a, int b);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};

#endif
