// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTODRIVEFORWARD_H
#define AUTODRIVEFORWARD_H
#define IN_PER_PULSE .003
#define PULSE_PER_IN 1/.003

#include "Commands/Subsystem.h"
#include "../../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutoDriveForward: public Command {
public:
	AutoDriveForward(double speed, double inches);
	AutoDriveForward(double lSpeed, double rSpeed, double lInches, double rInches);

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	int m_startTicksLeft;
	int m_startTicksRight;
	int m_lTicks;
	int m_rTicks;
	double m_lInches;
	double m_rInches;
	double m_lSpeed;
	double m_rSpeed;
};

#endif
