// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoDriveForward.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoDriveForward::AutoDriveForward(double speed, double inches): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_speed = speed;
	m_inches = inches;
	m_ticks = m_inches * TICKS_PER_INCH;
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoDriveForward::Initialize() {
	m_startTicksLeft = Robot::drive->GetLeftEnc();
	m_startTicksRight = Robot::drive->GetRightEnc();
	if (m_ticks < 0 && m_speed > 0)
	{
		m_speed = m_speed * -1;
	}
}

// Called repeatedly when this Command is scheduled to run
void AutoDriveForward::Execute() {
	Robot::drive->TankDrive(m_speed, m_speed);
}

// Make this return true when this Command no longer needs to run execute()
bool AutoDriveForward::IsFinished() {
	return (fabs(Robot::drive->GetLeftEnc() - m_startTicksLeft) > fabs(m_ticks) && fabs(Robot::drive->GetRightEnc() - m_startTicksRight) > fabs(m_ticks));
}

// Called once after isFinished returns true
void AutoDriveForward::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoDriveForward::Interrupted() {

}
