// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef JOYSTICKFIELDDRIVE_H
#define JOYSTICKFIELDDRIVE_H


#include "Commands/Subsystem.h"
#include "../../Robot.h"

/**
 * A field oriented drive.
 *
 * @author ExampleAuthor
 */
class JoystickFieldDrive: public Command {
public:
	JoystickFieldDrive();


	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	int mod(int a, int n);
	double angle_diff(int a, int b);

};

#endif
