// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ArmDriveToPos.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ArmDriveToPos::ArmDriveToPos(Arm::Position pos): Command() {

	m_position = pos;
	Requires(Robot::arm.get());

}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ArmDriveToPos::Initialize() {
	Robot::arm->ArmToPos(m_position);
	if(Robot::arm->GetArmPos() < ARM_ASSIST_POINT && Robot::arm->GetPotValueForPos(m_position) > ARM_ASSIST_POINT) {
		Robot::arm->ArmAssist(true);
	}
	else {
		Robot::arm->ArmAssist(false);
	}
}

// Called repeatedly when this Command is scheduled to run
void ArmDriveToPos::Execute() {
	SmartDashboard::PutNumber("arm_pot_current", Robot::arm->GetArmPos());
	SmartDashboard::PutString("auto_stage", "Arm Drive");
}

// Make this return true when this Command no longer needs to run execute()
bool ArmDriveToPos::IsFinished() {
    return fabs(Robot::oi->GetYControl()) > 0 || Robot::arm->IsArmAtPoint(m_position);
}

// Called once after isFinished returns true
void ArmDriveToPos::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ArmDriveToPos::Interrupted() {

}
